export const tokens = {
  bg0: "#04060a",
  bg1: "#080c12",
  bg2: "#0c1018",
  bg3: "#10151f",
  surface: "#141926",
  border: "rgba(255,255,255,0.06)",
  borderActive: "rgba(255,255,255,0.12)",
  text1: "#eef0f7",
  text2: "#8892a8",
  text3: "#3e4557",
  accent: "#3d7eff",
  accentDim: "rgba(61,126,255,0.10)",
  accentBorder: "rgba(61,126,255,0.22)",
  accentGlow: "rgba(61,126,255,0.50)",
  cyan: "#22d3ee",
  green: "#10b981",
  amber: "#f59e0b",
} as const;

export const projects = [
  {
    id: "placewise",
    slug: "placewise",
    name: "PlaceWise",
    category: "AI Product",
    icon: "/icon.png",
    featured: true,
    hasDetail: true,
    impact: "AI placement readiness engine for student career growth.",
    description:
      "AI-powered resume analyzer that uses RAG pipelines, vector search and LLMs to evaluate placement readiness, identify skill gaps and generate personalized improvement roadmaps.",
    stack: ["RAG", "ChromaDB", "FastAPI", "Groq LLM", "Resume Parsing"],
    highlights: ["RAG Architecture", "ATS-style Evaluation", "Skill Gap Roadmaps"],
    metric: "AI readiness scoring",
    status: "Currently building",
    problem:
      "Students often do not know why a resume is weak, how placement-ready they are, or which skills to improve first.",
    does:
      "Analyzes resumes with RAG, vector search, and LLM feedback to create readiness scores and personal improvement roadmaps.",
    solution:
      "PlaceWise turns resumes into structured intelligence with parsing, vector search, LLM evaluation, and personalized roadmaps.",
    architecture: ["Resume Parser", "FastAPI Evaluation API", "ChromaDB Vector Store", "Groq LLM Layer", "Roadmap Generator"],
    challenges: ["Designing useful scoring criteria", "Keeping LLM feedback structured", "Mapping resume gaps to actionable next steps"],
    outcomes: ["Placement readiness scoring", "ATS-style resume feedback", "Personalized improvement plans"],
    roadmap: ["GitHub profile analysis", "Interview question generation", "College placement dashboard"],
    year: "2026",
    github: "https://github.com/vishnu062006/placewise",
    demo: "https://placewise-ai.vercel.app",
    image: "/placewise.png",
  },
  {
    id: "eventara",
    slug: "eventara",
    name: "Eventara",
    category: "SaaS Platform",
    icon: "EV",
    featured: true,
    hasDetail: false,
    impact: "Scalable event operations from creation to registration.",
    description:
      "Full-stack event management platform enabling event creation, registration, participant management and scalable organization workflows.",
    stack: ["React", "Node.js", "Express.js", "MongoDB", "Auth"],
    highlights: ["Authentication", "Event Registration", "Dashboard System"],
    metric: "Organizer workflow system",
    status: "In development",
    problem:
      "Campus and community events need simple creation, registration, participant tracking, and organizer dashboards in one workflow.",
    does:
      "Gives organizers a full-stack event workspace for publishing events, handling registrations, and managing participants.",
    solution:
      "Eventara provides a full-stack event operations layer with authentication, event setup, registrations, and dashboard views.",
    architecture: ["React Dashboard", "Authentication Layer", "Event API", "Registration Flow", "Participant Management"],
    challenges: ["Designing organizer-first workflows", "Handling event states clearly", "Keeping dashboards scannable"],
    outcomes: ["Centralized event management", "Cleaner participant workflows", "Reusable SaaS-style architecture"],
    roadmap: ["Analytics dashboard", "QR-based check-ins", "Team-based organizer roles"],
    year: "2026",
    github: "https://github.com/vishnu062006/eventara-frontend",
    demo: "https://theeventara.vercel.app",
    image: "/eventara.png",
  },
  {
    id: "campusmart",
    slug: "campusmart",
    name: "Campus Mart",
    category: "Marketplace",
    icon: "CM",
    featured: true,
    hasDetail: true,
    impact: "Campus-native marketplace for student buying and selling.",
    description:
      "Student marketplace platform allowing users to buy, sell and discover products within a campus ecosystem.",
    stack: ["React", "Tailwind", "Node.js", "Express.js", "MongoDB", "JWT"],
    highlights: ["Listings", "Search", "User Profiles"],
    metric: "Peer-to-peer campus commerce",
    status: "Built",
    problem:
      "Students need a trusted campus-only way to discover, buy, and sell useful products without noisy general marketplaces.",
    does:
      "Creates a campus marketplace with listings, search, user profiles, authentication, and peer-to-peer commerce flows.",
    solution:
      "Campus Mart creates a student marketplace with listings, search, profiles, authentication, and campus commerce flows.",
    architecture: ["React Frontend", "Node + Express API", "MongoDB Listings", "JWT Authentication", "Cloudinary Media"],
    challenges: ["Designing trustworthy listing flows", "Balancing search and discovery", "Managing authenticated marketplace actions"],
    outcomes: ["Campus listing experience", "Reusable marketplace model", "Full-stack CRUD and auth foundation"],
    roadmap: ["Saved searches", "Chat between buyers and sellers", "Campus verification layer"],
    year: "2025",
    github: "https://github.com/vishnu062006",
    demo: "https://placewise-ai.vercel.app",
    image: "/campusmart.png",
  },
  {
    id: "microinternship",
    slug: "microinternship",
    name: "MicroInternship",
    category: "Career Platform",
    icon: "MI",
    featured: false,
    hasDetail: false,
    impact: "Short-form career opportunities for student momentum.",
    description:
      "Platform helping students discover and engage with micro-internship opportunities and career-building experiences.",
    stack: ["React", "Node.js", "REST API", "MongoDB", "UX Systems"],
    highlights: ["Opportunity Discovery", "Student Focused Design", "Career Growth Ecosystem"],
    metric: "Career discovery layer",
    status: "Concept to product",
    problem:
      "Students often miss smaller career-building experiences because opportunities are fragmented across groups and platforms.",
    does:
      "Organizes micro-internships, short projects, and career-building opportunities into a focused student discovery platform.",
    solution:
      "MicroInternship organizes short-form internships, projects, and skill-building opportunities into a focused student ecosystem.",
    architecture: ["Opportunity Feed", "Student Profiles", "Matching Logic", "Application Workflow", "Career Progress Layer"],
    challenges: ["Creating a useful discovery model", "Prioritizing student fit", "Designing lightweight opportunity workflows"],
    outcomes: ["Opportunity discovery system", "Student-focused product direction", "Career growth ecosystem foundation"],
    roadmap: ["Recommendation engine", "Mentor dashboards", "Verified opportunity partners"],
    year: "2026",
    github: "https://github.com/vishnu062006",
    demo: "#",
    image: "/microint.png",
  },
] as const;

export const skillGroups = [
  {
    title: "Frontend",
    color: "#3d7eff",
    skills: [
      { name: "React.js",          pct: 88, level: "Proficient" },
      { name: "Next.js",           pct: 76, level: "Building" },
      { name: "TypeScript",        pct: 72, level: "Building" },
      { name: "Tailwind CSS",      pct: 85, level: "Proficient" },
    ],
  },
  {
    title: "Backend",
    color: "#22d3ee",
    skills: [
      { name: "Node.js",           pct: 70, level: "Familiar" },
      { name: "Express.js",        pct: 68, level: "Familiar" },
      { name: "FastAPI",           pct: 70, level: "Familiar" },
      { name: "Spring Boot",       pct: 56, level: "Learning" },
      { name: "REST API Design",   pct: 73, level: "Familiar" },
    ],
  },
  {
    title: "AI",
    color: "#8b5cf6",
    skills: [
      { name: "RAG Pipelines",      pct: 72, level: "Building" },
      { name: "ChromaDB",           pct: 64, level: "Learning" },
      { name: "Groq",               pct: 70, level: "Building" },
      { name: "Prompt Engineering", pct: 78, level: "Building" },
    ],
  },
  {
    title: "Tools",
    color: "#10b981",
    skills: [
      { name: "MongoDB",           pct: 70, level: "Familiar" },
      { name: "MySQL",             pct: 65, level: "Familiar" },
      { name: "Supabase",          pct: 55, level: "Learning" },
      { name: "Git & GitHub",      pct: 82, level: "Proficient" },
      { name: "Postman",           pct: 72, level: "Familiar"   },
      { name: "Vercel",            pct: 66, level: "Familiar"   },
    ],
  },
] as const;
