export const tokens = {
  bg0: "#04060a",
  bg1: "#080c12",
  bg2: "#0c1018",
  bg3: "#10151f",
  surface: "#141926",
  border: "rgba(255,255,255,0.06)",
  borderActive: "rgba(255,255,255,0.12)",
  text1: "#eef0f7",
  text2: "#8892a8",
  text3: "#3e4557",
  accent: "#3d7eff",
  accentDim: "rgba(61,126,255,0.10)",
  accentBorder: "rgba(61,126,255,0.22)",
  accentGlow: "rgba(61,126,255,0.50)",
  cyan: "#22d3ee",
  green: "#10b981",
  amber: "#f59e0b",
} as const;

export const projects = [
  {
    id: "placewise",
    name: "PlaceWise",
    category: "AI Product",
    icon: "PW",
    featured: true,
    hasDetail: true,
    impact: "AI placement readiness engine for student career growth.",
    description:
      "AI-powered resume analyzer that uses RAG pipelines, vector search and LLMs to evaluate placement readiness, identify skill gaps and generate personalized improvement roadmaps.",
    stack: ["RAG", "ChromaDB", "FastAPI", "Groq LLM", "Resume Parsing"],
    highlights: ["RAG Architecture", "ATS-style Evaluation", "Skill Gap Roadmaps"],
    metric: "AI readiness scoring",
    year: "2026",
    github: "https://github.com/vishnu062006",
    demo: "#",
  },
  {
    id: "eventara",
    name: "Eventara",
    category: "SaaS Platform",
    icon: "EV",
    featured: true,
    hasDetail: false,
    impact: "Scalable event operations from creation to registration.",
    description:
      "Full-stack event management platform enabling event creation, registration, participant management and scalable organization workflows.",
    stack: ["React", "Node.js", "Express.js", "MongoDB", "Auth"],
    highlights: ["Authentication", "Event Registration", "Dashboard System"],
    metric: "Organizer workflow system",
    year: "2026",
    github: "https://github.com/vishnu062006",
    demo: "#",
  },
  {
    id: "campusmart",
    name: "Campus Mart",
    category: "Marketplace",
    icon: "CM",
    featured: true,
    hasDetail: true,
    impact: "Campus-native marketplace for student buying and selling.",
    description:
      "Student marketplace platform allowing users to buy, sell and discover products within a campus ecosystem.",
    stack: ["React", "Tailwind", "Node.js", "Express.js", "MongoDB", "JWT"],
    highlights: ["Listings", "Search", "User Profiles"],
    metric: "Peer-to-peer campus commerce",
    year: "2025",
    github: "https://github.com/vishnu062006",
    demo: "#",
  },
  {
    id: "microinternship",
    name: "MicroInternship",
    category: "Career Platform",
    icon: "MI",
    featured: false,
    hasDetail: false,
    impact: "Short-form career opportunities for student momentum.",
    description:
      "Platform helping students discover and engage with micro-internship opportunities and career-building experiences.",
    stack: ["React", "Node.js", "REST API", "MongoDB", "UX Systems"],
    highlights: ["Opportunity Discovery", "Student Focused Design", "Career Growth Ecosystem"],
    metric: "Career discovery layer",
    year: "2026",
    github: "https://github.com/vishnu062006",
    demo: "#",
  },
] as const;

export const skillGroups = [
  {
    title: "Frontend",
    color: "#3d7eff",
    skills: [
      { name: "React.js",          pct: 88, level: "Proficient" },
      { name: "Tailwind CSS",      pct: 85, level: "Proficient" },
      { name: "JavaScript ES6+",   pct: 83, level: "Proficient" },
      { name: "HTML5 / CSS3",      pct: 91, level: "Strong"     },
      { name: "React Router",      pct: 74, level: "Familiar"   },
    ],
  },
  {
    title: "Backend",
    color: "#22d3ee",
    skills: [
      { name: "Node.js",           pct: 70, level: "Familiar" },
      { name: "Express.js",        pct: 68, level: "Familiar" },
      { name: "REST API Design",   pct: 73, level: "Familiar" },
      { name: "Java",              pct: 56, level: "Learning" },
      { name: "Python",            pct: 55, level: "Learning" },
    ],
  },
  {
    title: "AI / ML",
    color: "#8b5cf6",
    skills: [
      { name: "RAG Pipelines",      pct: 72, level: "Building" },
      { name: "LLM Integrations",   pct: 76, level: "Building" },
      { name: "FastAPI",            pct: 70, level: "Familiar" },
      { name: "ChromaDB",           pct: 64, level: "Learning" },
      { name: "Prompt Workflows",   pct: 78, level: "Building" },
    ],
  },
  {
    title: "Databases",
    color: "#10b981",
    skills: [
      { name: "MongoDB",           pct: 70, level: "Familiar" },
      { name: "MySQL",             pct: 65, level: "Familiar" },
      { name: "Mongoose ODM",      pct: 68, level: "Familiar" },
    ],
  },
  {
    title: "Dev Tools",
    color: "#f59e0b",
    skills: [
      { name: "Git & GitHub",      pct: 82, level: "Proficient" },
      { name: "VS Code",           pct: 92, level: "Daily"      },
      { name: "Postman",           pct: 72, level: "Familiar"   },
      { name: "Vercel / Netlify",  pct: 66, level: "Familiar"   },
    ],
  },
] as const;
